"""empty message

Revision ID: bfdffb257f72
Revises: dd6b0c2aadce
Create Date: 2024-07-17 10:07:04.900933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdffb257f72'
down_revision = 'dd6b0c2aadce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skill_level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'age_group', ['age_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'skill_level', ['skill_level_id'], ['id'])
        batch_op.drop_column('age_group')
        batch_op.drop_column('skill_level')

    with op.batch_alter_table('partner_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.String(length=50), nullable=True))
        batch_op.alter_column('interest',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('relationship_level',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('matching_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('age')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('partner_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.alter_column('matching_type',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('relationship_level',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('interest',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('age_group')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skill_level_id')
        batch_op.drop_column('age_group_id')

    op.drop_table('skill_level')
    op.drop_table('age_group')
    # ### end Alembic commands ###
